# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: 
        # name our filter set "my_thumb_filter"
        my_thumb:
            quality: 100
            filters:
                # use and setup the "thumbnail" filter
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [350, 350] 
                    # crop the input image, if required
                    mode: outbound
                scale:
                    dim: [450, 450]
        
        my_thumb_product:
            quality: 100
            filters:
                # use and setup the "thumbnail" filter
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [600, 350] 
                    # crop the input image, if required
                    mode: outbound
                scale:
                    dim: [600, 600]
    twig:
        mode:             legacy
    default_filter_set_settings:
        quality:              100
        jpeg_quality:         ~
        png_compression_level:  9
        png_compression_filter: ~
        animated:             false
        format:               ~
        cache:                ~
        data_loader:          ~
        default_image:        null
        filters: []
        post_processors: []