#test:
    #path: /test/{age<\d+>?0}
    #controller: App\Controller\TestController::test
    #methods: [GET, POST]
    #host: localhost
    #schemes: [https, http]
    #api.monsite.com/ www.monsite.com/monsite.com
    #defaults:
        #age: 0
    #requirements:
        #age: \d+